openapi: 3.0.3
info:
  title: Dream Mail GO
  description: |-
    A coding challenge generic email service that can be spun up to send emails through HTTP API calls
  contact:
    email: gugabfigueiredo@gmail.com
  license:
    name: MIT
    url: https://choosealicense.com/licenses/mit/
  version: 0.1.0
paths:
  /dream-mail-go/send:
    post:
      summary: Send an email
      description: Will take an email and queue it for delivery
      requestBody:
        description: send an email
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mail'
        required: true
      responses:
        '200':
          description: Email queued for delivery
        '400':
          description: Invalid or corrupted email data
        '500':
          description: Internal server error
components:
  schemas:
    Mail:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        from:
          $ref: '#/components/schemas/Email'
        to:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/Email'
        subject:
          type: string
          example: 'Hello World'
        text:
          type: string
          example: 'Hello World'
        html:
          type: string
          example: '<h1>Hello World</h1>'
        attachments:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/Attachment'
    Email:
      type: object
      properties:
        name:
          type: string
          example: 'John Doe'
        addr:
          type: string
          example: 'example@domain.com'
    Attachment:
      type: object
      properties:
        name:
          type: string
          example: 'file.txt'
        data:
          type: string
          example: 'SGVsbG8gV29ybGQ='
        type:
          type: string
          description: MIME type
          example: 'text/plain'